package com.aringeri.crashdata.db
import scalikejdbc._

final case class Vehicle(
  accidentNo: String,
  vehicleId: String,
  vehicleYearManuf: String,
  vehicleDcaCode: String,
  initialDirection: String,
  roadSurfaceType: String,
  roadSurfaceTypeDesc: String,
  regState: String,
  vehicleBodyStyle: String,
  vehicleMake: String,
  vehicleModel: String,
  vehiclePower: String,
  vehicleType: Int,
  vehicleTypeDesc: String,
  vehicleWeight: String,
  constructionType: String,
  fuelType: String,
  noOfWheels: String,
  noOfCylinders: String,
  seatingCapacity: String,
  tareWeight: String,
  totalNoOccupants: String,
  carryCapacity: String,
  cubicCapacity: String,
  finalDirection: String,
  driverIntent: String,
  vehicleMovement: String,
  trailerType: String,
  vehicleColour1: String,
  vehicleColour2: String,
  caughtFire: String,
  initialImpact: String,
  lamps: String,
  levelOfDamage: String,
  ownerPostcode: String,
  towedAwayFlag: String,
  trafficControl: String,
  trafficControlDesc: String)

object Vehicle extends SQLSyntaxSupport[Vehicle] {
  override val tableName = "vehicle"
  def apply(v: ResultName[Vehicle])(rs: WrappedResultSet) = new Vehicle(
    rs.string(v.accidentNo),
    rs.string(v.vehicleId),
    rs.string(v.vehicleYearManuf),
    rs.string(v.vehicleDcaCode),
    rs.string(v.initialDirection),
    rs.string(v.roadSurfaceType),
    rs.string(v.roadSurfaceTypeDesc),
    rs.string(v.regState),
    rs.string(v.vehicleBodyStyle),
    rs.string(v.vehicleMake),
    rs.string(v.vehicleModel),
    rs.string(v.vehiclePower),
    rs.int(v.vehicleType),
    rs.string(v.vehicleTypeDesc),
    rs.string(v.vehicleWeight),
    rs.string(v.constructionType),
    rs.string(v.fuelType),
    rs.string(v.noOfWheels),
    rs.string(v.noOfCylinders),
    rs.string(v.seatingCapacity),
    rs.string(v.tareWeight),
    rs.string(v.totalNoOccupants),
    rs.string(v.carryCapacity),
    rs.string(v.cubicCapacity),
    rs.string(v.finalDirection),
    rs.string(v.driverIntent),
    rs.string(v.vehicleMovement),
    rs.string(v.trailerType),
    rs.string(v.vehicleColour1),
    rs.string(v.vehicleColour2),
    rs.string(v.caughtFire),
    rs.string(v.initialImpact),
    rs.string(v.lamps),
    rs.string(v.levelOfDamage),
    rs.string(v.ownerPostcode),
    rs.string(v.towedAwayFlag),
    rs.string(v.trafficControl),
    rs.string(v.trafficControlDesc)
  )
}
    